# MediaPipe graph to detect faces. (CPU input and inference, with region-of-interest.)
#
# EXAMPLE:
#   node {
#     calculator: "FaceDetectionShortRangeByRoiCpu"
#     input_stream: "IMAGE:image"
#     output_stream: "DETECTIONS:face_detections"
#   }
type: "FaceDetectionShortRangeByRoiCpu"

# The input image, either ImageFrame, or (multi-backend) Image.
input_stream: "IMAGE:image"

# ROI (region of interest) within the given image where faces should be
# detected. (NormalizedRect)
input_stream: "ROI:roi"

# Detected faces. (std::vector<Detection>)
output_stream: "DETECTIONS:detections"

graph_options: {
  [type.googleapis.com/mediapipe.FaceDetectionOptions] {}
}

node {
  calculator: "ConstantSidePacketCalculator"
  output_side_packet: "PACKET:model_path"
  node_options: {
    [type.googleapis.com/mediapipe.ConstantSidePacketCalculatorOptions]: {
      packet {
        string_value: "mediapipe/modules/face_detection/face_detection_short_range.tflite"
      }
    }
  }
}

node {
  calculator: "FaceDetectionShortRange"
  input_stream: "IMAGE:image"
  input_stream: "ROI:roi"
  input_side_packet: "MODEL_PATH:model_path"
  output_stream: "DETECTIONS:detections"
  node_options: {
    [type.googleapis.com/mediapipe.FaceDetectionOptions] {
      delegate { xnnpack {} }
    }
  }
  option_value: "OPTIONS:options"
}
